# fly.toml app configuration file generated for kwokpia-hello-fly on 2025-05-12T10:36:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kwokpia-hello-fly'
primary_region = 'hkg'
regions = [
  'iad',
  'ord',
  'lax',
  'scl',
  'gdl',
  'ams',
  'fra',
  'lhr',
  'nrt',
  'sin',
  'bom',
  'syd',
  'jnb',
]

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
